### ISSUE TITLE
Can't be used in landscape format

### ISSUE THREAD

**Issue by zafyraminx** [choiboi/android-cropping-example#9]
I am trying to fix this bug but i dont know how, i am working with it for tha past few days, it is okey with porttrait but in landscape i am always having a error.

02-23 08:18:45.335: E/AndroidRuntime(30289): FATAL EXCEPTION: Thread-10
02-23 08:18:45.335: E/AndroidRuntime(30289): java.lang.IllegalArgumentException: y must be < bitmap.height()
02-23 08:18:45.335: E/AndroidRuntime(30289): 	at android.graphics.Bitmap.checkPixelAccess(Bitmap.java:797)
02-23 08:18:45.335: E/AndroidRuntime(30289): 	at android.graphics.Bitmap.getPixel(Bitmap.java:749)
02-23 08:18:45.335: E/AndroidRuntime(30289): 	at com.choiboi.imagecroppingexample.ImageProcess.cropImageVer2_1(ImageProcess.java:921)
02-23 08:18:45.335: E/AndroidRuntime(30289): 	at com.choiboi.imagecroppingexample.CropActivity$6.run(CropActivity.java:440)
02-23 08:18:45.335: E/AndroidRuntime(30289): 	at java.lang.Thread.run(Thread.java:1019)
02-23 08:18:47.425: E/WindowManager(30289): Activity com.choiboi.imagecroppingexample.CropActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView@40532fc8 that was originally added here
02-23 08:18:47.425: E/WindowManager(30289): android.view.WindowLeaked: Activity com.choiboi.imagecroppingexample.CropActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView@40532fc8 that was originally added here
02-23 08:18:47.425: E/WindowManager(30289): 	at android.view.ViewRoot.<init>(ViewRoot.java:258)
02-23 08:18:47.425: E/WindowManager(30289): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
02-23 08:18:47.425: E/WindowManager(30289): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
02-23 08:18:47.425: E/WindowManager(30289): 	at android.view.Window$LocalWindowManager.addView(Window.java:424)
02-23 08:18:47.425: E/WindowManager(30289): 	at android.app.Dialog.show(Dialog.java:241)
02-23 08:18:47.425: E/WindowManager(30289): 	at com.choiboi.imagecroppingexample.CropActivity.onCropImageButton(CropActivity.java:411)
02-23 08:18:47.425: E/WindowManager(30289): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-23 08:18:47.425: E/WindowManager(30289): 	at java.lang.reflect.Method.invoke(Method.java:507)
02-23 08:18:47.425: E/WindowManager(30289): 	at android.view.View$1.onClick(View.java:2139)
02-23 08:18:47.425: E/WindowManager(30289): 	at android.view.View.performClick(View.java:2485)
02-23 08:18:47.425: E/WindowManager(30289): 	at android.view.View$PerformClick.run(View.java:9080)
02-23 08:18:47.425: E/WindowManager(30289): 	at android.os.Handler.handleCallback(Handler.java:587)
02-23 08:18:47.425: E/WindowManager(30289): 	at android.os.Handler.dispatchMessage(Handler.java:92)
02-23 08:18:47.425: E/WindowManager(30289): 	at android.os.Looper.loop(Looper.java:123)
02-23 08:18:47.425: E/WindowManager(30289): 	at android.app.ActivityThread.main(ActivityThread.java:3683)
02-23 08:18:47.425: E/WindowManager(30289): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-23 08:18:47.425: E/WindowManager(30289): 	at java.lang.reflect.Method.invoke(Method.java:507)
02-23 08:18:47.425: E/WindowManager(30289): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
02-23 08:18:47.425: E/WindowManager(30289): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
02-23 08:18:47.425: E/WindowManager(30289): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by choiboi** [comment]
Hi there, I've never tested it in landscape mode, thus as you witness there will be errors.
Thanks.

**Comment by zafyraminx** [comment]
It's okey now. Sorry for the disturb, anyways thank you. Your sample is really good.

**Comment by choiboi** [comment]
I believe you can still use this code in landscape mode, the only thing that needs to be changed is that the correct values are being used in the cropping algorithm.
